version: '3'

services:
  frontend:
    image: sainiji/ms-frontend:1.0 
    restart: always
    ports:
      - "3000:3000"

  products:
    image: sainiji/ms-products:1.0
    restart: always  
    ports:
      - "3001:3001"

  shopping-cart:
    image: sainiji/ms-shopping-cart:1.0
    restart: always  
    ports:
      - "3002:3002"

  nginx:
    image: nginx
    ports:
      - "80:80"


    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - products
      - shopping-cart

